version: '3.8'

services:
  autorag:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    tty: true

volumes:
  qdrant_storage:
  ollama_storage:
